/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/top": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTopEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{event_type}/{start_time}/{problem}/{event_id}/{source}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getEventDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/features/top": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTopFeatures"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/features/countries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCountryFeatures"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/features/ases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAsFeatures"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/features/outages/country-as": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCountryAsOutages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/features/outages/country-prefix": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCountryPrefixOutages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/features/outages/as-prefix": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAsPrefixOutages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/features/outages/global-as": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getGlobalAsOutages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/features/outages/global-prefix": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getGlobalPrefixOutages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/counts/total": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getEventCounts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/counts/type": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTypeCount"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthPayload: {
            status: string;
            service: string;
            time: string;
        };
        EventItem: {
            event_type: string;
            level: string;
            start_time: string;
            end_time: string;
            attacker_as: string;
            attacked_as: string;
            event_info: string;
            detail_url: string;
            affected_prefix: string;
            attacker_org: string;
            attacked_org: string;
            attacker_country: string;
            attacked_country: string;
        } & {
            [key: string]: unknown;
        };
        EventPage: {
            data: components["schemas"]["EventItem"][];
            total_page: number;
            record_count: string;
        };
        EventDetail: {
            start_time: string;
            end_time: string;
            duration: string;
            event_level: string;
            event_descr: string;
            event_info: string;
        } & {
            [key: string]: unknown;
        };
        FeaturePoint: {
            t: string;
            asn?: string;
            announce: number;
            withdraw: number;
            v4Prefix_num?: number | null;
            v6Prefix_num?: number | null;
            v4IP_num?: number | null;
        };
        FeatureSeriesPoint: {
            time: string;
            announce: number;
            withdraw: number;
            v4Prefix_num: number;
            v6Prefix_num: number;
            v4IP_num: number;
        };
        CountryFeatureItem: {
            country: string;
            time_series_data: components["schemas"]["FeatureSeriesPoint"][];
        };
        AsFeatureItem: {
            asn: string;
            as_name: string;
            country: string;
            org_name: string;
            time_series_data: components["schemas"]["FeatureSeriesPoint"][];
        };
        CountryFeaturePage: {
            total_page: number;
            record_count: number;
            current_page: number;
            page_size: number;
            data: components["schemas"]["CountryFeatureItem"][];
        };
        AsFeaturePage: {
            total_page: number;
            record_count: number;
            current_page: number;
            page_size: number;
            data: components["schemas"]["AsFeatureItem"][];
        };
        OutagePoint: {
            time_slot: string;
            outage_count: number;
        };
        CountPoint: {
            time: string;
            num: number;
        };
        TypeCount: {
            event_type: string;
            num: number;
            amplitude_type: boolean;
            amplitude: string;
            icon: string;
        };
    };
    responses: {
        /** @description 中断时序 */
        OutageSeries: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["OutagePoint"][];
            };
        };
    };
    parameters: {
        StartTime: string;
        EndTime: string;
        Target: string;
        Country: string;
        PageNum: number;
        FeaturePageSize: 5 | 10 | 20 | 50;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 服务正常 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthPayload"];
                };
            };
        };
    };
    getEvents: {
        parameters: {
            query?: {
                page_num?: number;
                page_size?: 10 | 50 | 100 | 200;
                event_type?: string;
                level?: string;
                country?: string;
                event_info?: string;
                date?: string;
                sort_mode?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 分页事件 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventPage"];
                };
            };
        };
    };
    getTopEvents: {
        parameters: {
            query?: {
                event_type?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 最新事件 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventItem"][];
                };
            };
        };
    };
    getEventDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_type: "hijack" | "sub_hijack" | "prefix_outage" | "as_outage" | "country_outage" | "leak";
                start_time: string;
                problem: string;
                event_id: number;
                source: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 事件事实与路径证据 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventDetail"];
                };
            };
        };
    };
    getTopFeatures: {
        parameters: {
            query: {
                target: components["parameters"]["Target"];
                start_time: components["parameters"]["StartTime"];
                end_time: components["parameters"]["EndTime"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 特征时序 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeaturePoint"][];
                };
            };
        };
    };
    getCountryFeatures: {
        parameters: {
            query: {
                country?: string;
                page_num?: components["parameters"]["PageNum"];
                page_size?: components["parameters"]["FeaturePageSize"];
                start_time: components["parameters"]["StartTime"];
                end_time: components["parameters"]["EndTime"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 国家特征分页 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CountryFeaturePage"];
                };
            };
        };
    };
    getAsFeatures: {
        parameters: {
            query: {
                asn?: string;
                country?: string;
                page_num?: components["parameters"]["PageNum"];
                page_size?: components["parameters"]["FeaturePageSize"];
                start_time: components["parameters"]["StartTime"];
                end_time: components["parameters"]["EndTime"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ASN 特征分页 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AsFeaturePage"];
                };
            };
        };
    };
    getCountryAsOutages: {
        parameters: {
            query: {
                country: components["parameters"]["Country"];
                start_time: components["parameters"]["StartTime"];
                end_time: components["parameters"]["EndTime"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["OutageSeries"];
        };
    };
    getCountryPrefixOutages: {
        parameters: {
            query: {
                country: components["parameters"]["Country"];
                start_time: components["parameters"]["StartTime"];
                end_time: components["parameters"]["EndTime"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["OutageSeries"];
        };
    };
    getAsPrefixOutages: {
        parameters: {
            query: {
                asn: string;
                start_time: components["parameters"]["StartTime"];
                end_time: components["parameters"]["EndTime"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["OutageSeries"];
        };
    };
    getGlobalAsOutages: {
        parameters: {
            query: {
                start_time: components["parameters"]["StartTime"];
                end_time: components["parameters"]["EndTime"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["OutageSeries"];
        };
    };
    getGlobalPrefixOutages: {
        parameters: {
            query: {
                start_time: components["parameters"]["StartTime"];
                end_time: components["parameters"]["EndTime"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["OutageSeries"];
        };
    };
    getEventCounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 每日事件数 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CountPoint"][];
                };
            };
        };
    };
    getTypeCount: {
        parameters: {
            query: {
                event_type: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 事件类型统计 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TypeCount"];
                };
            };
        };
    };
}
