export type CountryOption = {
  code: string;
  label: string;
  value: string;
  queryValue: string;
  sortKey: string;
};

export const COUNTRY_OPTIONS: CountryOption[] = [
  { code: 'AF', label: '阿富汗', value: '阿富汗', queryValue: '阿富汗', sortKey: 'Afghanistan' },
  { code: 'AX', label: '奥兰群岛', value: '奥兰群岛', queryValue: '奥兰', sortKey: 'Aland Islands' },
  { code: 'AL', label: '阿尔巴尼亚', value: '阿尔巴尼亚', queryValue: '阿尔巴尼亚', sortKey: 'Albania' },
  { code: 'DZ', label: '阿尔及利亚', value: '阿尔及利亚', queryValue: '阿尔及利亚', sortKey: 'Algeria' },
  { code: 'AS', label: '美属萨摩亚', value: '美属萨摩亚', queryValue: '美属萨摩亚', sortKey: 'American Samoa' },
  { code: 'AD', label: '安道尔', value: '安道尔', queryValue: '安道尔', sortKey: 'Andorra' },
  { code: 'AO', label: '安哥拉', value: '安哥拉', queryValue: '安哥拉', sortKey: 'Angola' },
  { code: 'AI', label: '安圭拉', value: '安圭拉', queryValue: '安圭拉', sortKey: 'Anguilla' },
  { code: 'AG', label: '安提瓜和巴布达', value: '安提瓜和巴布达', queryValue: '安提瓜和巴布达', sortKey: 'Antigua and Barbuda' },
  { code: 'AR', label: '阿根廷', value: '阿根廷', queryValue: '阿根廷', sortKey: 'Argentina' },
  { code: 'AM', label: '亚美尼亚', value: '亚美尼亚', queryValue: '亚美尼亚', sortKey: 'Armenia' },
  { code: 'AW', label: '阿鲁巴', value: '阿鲁巴', queryValue: '阿鲁巴', sortKey: 'Aruba' },
  { code: 'AP', label: '亚太地区', value: '亚太地区', queryValue: '亚太地区', sortKey: 'Asia Pacific' },
  { code: 'AU', label: '澳大利亚', value: '澳大利亚', queryValue: '澳大利亚', sortKey: 'Australia' },
  { code: 'AT', label: '奥地利', value: '奥地利', queryValue: '奥地利', sortKey: 'Austria' },
  { code: 'AZ', label: '阿塞拜疆', value: '阿塞拜疆', queryValue: '阿塞拜疆', sortKey: 'Azerbaijan' },
  { code: 'BS', label: '巴哈马', value: '巴哈马', queryValue: '巴哈马', sortKey: 'Bahamas' },
  { code: 'BH', label: '巴林', value: '巴林', queryValue: '巴林', sortKey: 'Bahrain' },
  { code: 'BD', label: '孟加拉国', value: '孟加拉国', queryValue: '孟加拉国', sortKey: 'Bangladesh' },
  { code: 'BB', label: '巴巴多斯', value: '巴巴多斯', queryValue: '巴巴多斯', sortKey: 'Barbados' },
  { code: 'BY', label: '白俄罗斯', value: '白俄罗斯', queryValue: '白俄罗斯', sortKey: 'Belarus' },
  { code: 'BE', label: '比利时', value: '比利时', queryValue: '比利时', sortKey: 'Belgium' },
  { code: 'BZ', label: '伯利兹', value: '伯利兹', queryValue: '伯利兹', sortKey: 'Belize' },
  { code: 'BJ', label: '贝宁', value: '贝宁', queryValue: '贝宁', sortKey: 'Benin' },
  { code: 'BM', label: '百慕大', value: '百慕大', queryValue: '百慕大', sortKey: 'Bermuda' },
  { code: 'BT', label: '不丹', value: '不丹', queryValue: '不丹', sortKey: 'Bhutan' },
  { code: 'BO', label: '玻利维亚', value: '玻利维亚', queryValue: '玻利维亚', sortKey: 'Bolivia' },
  { code: 'BA', label: '波黑', value: '波黑', queryValue: '波黑', sortKey: 'Bosnia and Herzegovina' },
  { code: 'BW', label: '博茨瓦纳', value: '博茨瓦纳', queryValue: '博茨瓦纳', sortKey: 'Botswana' },
  { code: 'BR', label: '巴西', value: '巴西', queryValue: '巴西', sortKey: 'Brazil' },
  { code: 'IO', label: '英属印度洋领地', value: '英属印度洋领地', queryValue: '英属印度洋领地', sortKey: 'British Indian Ocean Territory (the)' },
  { code: 'BN', label: '文莱', value: '文莱', queryValue: '文莱', sortKey: 'Brunei' },
  { code: 'BG', label: '保加利亚', value: '保加利亚', queryValue: '保加利亚', sortKey: 'Bulgaria' },
  { code: 'BF', label: '布基纳法索', value: '布基纳法索', queryValue: '布基纳法索', sortKey: 'Burkina Faso' },
  { code: 'MM', label: '缅甸', value: '缅甸', queryValue: '缅甸', sortKey: 'Burma (Myanmar)' },
  { code: 'BI', label: '布隆迪', value: '布隆迪', queryValue: '布隆迪', sortKey: 'Burundi' },
  { code: 'KH', label: '柬埔寨', value: '柬埔寨', queryValue: '柬埔寨', sortKey: 'Cambodia(Kampuchea)' },
  { code: 'CM', label: '喀麦隆', value: '喀麦隆', queryValue: '喀麦隆', sortKey: 'Cameroon' },
  { code: 'CA', label: '加拿大', value: '加拿大', queryValue: '加拿大', sortKey: 'Canada' },
  { code: 'CV', label: '佛得角', value: '佛得角', queryValue: '佛得角', sortKey: 'Cape Verde' },
  { code: 'BQ', label: '荷兰加勒比区', value: '荷兰加勒比区', queryValue: '荷兰加勒比区', sortKey: 'Caribbean Netherlands' },
  { code: 'KY', label: '开曼群岛', value: '开曼群岛', queryValue: '开曼群岛', sortKey: 'Cayman Islands' },
  { code: 'CF', label: '中非', value: '中非', queryValue: '中非', sortKey: 'Central African Republic' },
  { code: 'TD', label: '乍得', value: '乍得', queryValue: '乍得', sortKey: 'Chad' },
  { code: 'CL', label: '智利', value: '智利', queryValue: '智利', sortKey: 'Chile' },
  { code: 'CN', label: '中国', value: '中国', queryValue: '中国', sortKey: 'China' },
  { code: 'CO', label: '哥伦比亚', value: '哥伦比亚', queryValue: '哥伦比亚', sortKey: 'Colombia' },
  { code: 'KM', label: '科摩罗', value: '科摩罗', queryValue: '科摩罗', sortKey: 'Comoros' },
  { code: 'CG', label: '刚果（布）', value: '刚果（布）', queryValue: '刚果共和国', sortKey: 'Congo-Brazzaville' },
  { code: 'CD', label: '刚果（金）', value: '刚果（金）', queryValue: '刚果民主共和国', sortKey: 'Congo-kinshasa' },
  { code: 'CK', label: '库克群岛', value: '库克群岛', queryValue: '库克群岛', sortKey: 'Cook Islands' },
  { code: 'CR', label: '哥斯达黎加', value: '哥斯达黎加', queryValue: '哥斯达黎加', sortKey: 'Costa Rica' },
  { code: 'HR', label: '克罗地亚', value: '克罗地亚', queryValue: '克罗地亚', sortKey: 'Croatia' },
  { code: 'CU', label: '古巴', value: '古巴', queryValue: '古巴', sortKey: 'Cuba' },
  { code: 'CW', label: '库拉索', value: '库拉索', queryValue: '库拉索', sortKey: 'Curaçao' },
  { code: 'CY', label: '塞浦路斯', value: '塞浦路斯', queryValue: '塞浦路斯', sortKey: 'Cyprus' },
  { code: 'CZ', label: '捷克', value: '捷克', queryValue: '捷克', sortKey: 'Czech Republic' },
  { code: 'CI', label: '科特迪瓦', value: '科特迪瓦', queryValue: '科特迪瓦', sortKey: 'Côte d\'Ivoire' },
  { code: 'DK', label: '丹麦', value: '丹麦', queryValue: '丹麦', sortKey: 'Denmark' },
  { code: 'DJ', label: '吉布提', value: '吉布提', queryValue: '吉布提', sortKey: 'Djibouti' },
  { code: 'DM', label: '多米尼克', value: '多米尼克', queryValue: '多米尼克', sortKey: 'Dominica' },
  { code: 'DO', label: '多米尼加', value: '多米尼加', queryValue: '多米尼加', sortKey: 'Dominican Republic' },
  { code: 'EC', label: '厄瓜多尔', value: '厄瓜多尔', queryValue: '厄瓜多尔', sortKey: 'Ecuador' },
  { code: 'EG', label: '埃及', value: '埃及', queryValue: '埃及', sortKey: 'Egypt' },
  { code: 'SV', label: '萨尔瓦多', value: '萨尔瓦多', queryValue: '萨尔瓦多', sortKey: 'El Salvador' },
  { code: 'GQ', label: '赤道几内亚', value: '赤道几内亚', queryValue: '赤道几内亚', sortKey: 'Equatorial Guinea' },
  { code: 'ER', label: '厄立特里亚', value: '厄立特里亚', queryValue: '厄立特里亚', sortKey: 'Eritrea' },
  { code: 'EE', label: '爱沙尼亚', value: '爱沙尼亚', queryValue: '爱沙尼亚', sortKey: 'Estonia' },
  { code: 'ET', label: '埃塞俄比亚', value: '埃塞俄比亚', queryValue: '埃塞俄比亚', sortKey: 'Ethiopia' },
  { code: 'EU', label: '欧盟', value: '欧盟', queryValue: '欧盟', sortKey: 'European Union' },
  { code: 'FK', label: '福克兰群岛', value: '福克兰群岛', queryValue: '福克兰群岛', sortKey: 'Falkland Islands' },
  { code: 'FO', label: '法罗群岛', value: '法罗群岛', queryValue: '法罗群岛', sortKey: 'Faroe Islands (the)' },
  { code: 'FJ', label: '斐济', value: '斐济', queryValue: '斐济', sortKey: 'Fiji' },
  { code: 'FI', label: '芬兰', value: '芬兰', queryValue: '芬兰', sortKey: 'Finland' },
  { code: 'FR', label: '法国', value: '法国', queryValue: '法国', sortKey: 'France' },
  { code: 'GF', label: '法属圭亚那', value: '法属圭亚那', queryValue: '法属圭亚那', sortKey: 'French Guiana' },
  { code: 'PF', label: '法属波利尼西亚', value: '法属波利尼西亚', queryValue: '法属波利尼西亚', sortKey: 'French Polynesia' },
  { code: 'GA', label: '加蓬', value: '加蓬', queryValue: '加蓬', sortKey: 'Gabon' },
  { code: 'GM', label: '冈比亚', value: '冈比亚', queryValue: '冈比亚', sortKey: 'Gambia' },
  { code: 'GE', label: '格鲁吉亚', value: '格鲁吉亚', queryValue: '格鲁吉亚', sortKey: 'Georgia' },
  { code: 'DE', label: '德国', value: '德国', queryValue: '德国', sortKey: 'Germany' },
  { code: 'GH', label: '加纳', value: '加纳', queryValue: '加纳', sortKey: 'Ghana' },
  { code: 'GI', label: '直布罗陀', value: '直布罗陀', queryValue: '直布罗陀', sortKey: 'Gibraltar' },
  { code: 'GR', label: '希腊', value: '希腊', queryValue: '希腊', sortKey: 'Greece' },
  { code: 'GL', label: '格陵兰', value: '格陵兰', queryValue: '格陵兰', sortKey: 'Greenland' },
  { code: 'GD', label: '格林纳达', value: '格林纳达', queryValue: '格林纳达', sortKey: 'Grenada' },
  { code: 'GP', label: '瓜德罗普', value: '瓜德罗普', queryValue: '瓜德罗普', sortKey: 'Guadeloupe' },
  { code: 'GU', label: '关岛', value: '关岛', queryValue: '关岛', sortKey: 'Guam' },
  { code: 'GT', label: '危地马拉', value: '危地马拉', queryValue: '危地马拉', sortKey: 'Guatemala' },
  { code: 'GG', label: '格恩西岛', value: '格恩西岛', queryValue: '根西', sortKey: 'Guernsey' },
  { code: 'GN', label: '几内亚', value: '几内亚', queryValue: '几内亚', sortKey: 'Guinea' },
  { code: 'GW', label: '几内亚比绍', value: '几内亚比绍', queryValue: '几内亚比绍', sortKey: 'Guinea-Bissau' },
  { code: 'GY', label: '圭亚那', value: '圭亚那', queryValue: '圭亚那', sortKey: 'Guyana' },
  { code: 'HT', label: '海地', value: '海地', queryValue: '海地', sortKey: 'Haiti' },
  { code: 'HN', label: '洪都拉斯', value: '洪都拉斯', queryValue: '洪都拉斯', sortKey: 'Honduras' },
  { code: 'HK', label: '香港', value: '香港', queryValue: '香港', sortKey: 'Hong Kong' },
  { code: 'HU', label: '匈牙利', value: '匈牙利', queryValue: '匈牙利', sortKey: 'Hungary' },
  { code: 'IS', label: '冰岛', value: '冰岛', queryValue: '冰岛', sortKey: 'Iceland' },
  { code: 'IN', label: '印度', value: '印度', queryValue: '印度', sortKey: 'India' },
  { code: 'ID', label: '印度尼西亚', value: '印度尼西亚', queryValue: '印度尼西亚', sortKey: 'Indonesia' },
  { code: 'IR', label: '伊朗', value: '伊朗', queryValue: '伊朗', sortKey: 'Iran' },
  { code: 'IQ', label: '伊拉克', value: '伊拉克', queryValue: '伊拉克', sortKey: 'Iraq' },
  { code: 'IE', label: '爱尔兰', value: '爱尔兰', queryValue: '爱尔兰', sortKey: 'Ireland' },
  { code: 'IM', label: '马恩岛', value: '马恩岛', queryValue: '马恩岛', sortKey: 'Isle of Man' },
  { code: 'IL', label: '以色列', value: '以色列', queryValue: '以色列', sortKey: 'Israel' },
  { code: 'IT', label: '意大利', value: '意大利', queryValue: '意大利', sortKey: 'Italy' },
  { code: 'JM', label: '牙买加', value: '牙买加', queryValue: '牙买加', sortKey: 'Jamaica' },
  { code: 'JP', label: '日本', value: '日本', queryValue: '日本', sortKey: 'Japan' },
  { code: 'JE', label: '泽西岛', value: '泽西岛', queryValue: '泽西', sortKey: 'Jersey' },
  { code: 'JO', label: '约旦', value: '约旦', queryValue: '约旦', sortKey: 'Jordan' },
  { code: 'KZ', label: '哈萨克斯坦', value: '哈萨克斯坦', queryValue: '哈萨克斯坦', sortKey: 'Kazakhstan' },
  { code: 'KE', label: '肯尼亚', value: '肯尼亚', queryValue: '肯尼亚', sortKey: 'Kenya' },
  { code: 'KI', label: '基里巴斯', value: '基里巴斯', queryValue: '基里巴斯', sortKey: 'Kiribati' },
  { code: 'KW', label: '科威特', value: '科威特', queryValue: '科威特', sortKey: 'Kuwait' },
  { code: 'KG', label: '吉尔吉斯斯坦', value: '吉尔吉斯斯坦', queryValue: '吉尔吉斯斯坦', sortKey: 'Kyrgyzstan' },
  { code: 'LA', label: '老挝', value: '老挝', queryValue: '老挝', sortKey: 'Lao People\'s Democratic Republic' },
  { code: 'LV', label: '拉脱维亚', value: '拉脱维亚', queryValue: '拉脱维亚', sortKey: 'Latvia' },
  { code: 'LB', label: '黎巴嫩', value: '黎巴嫩', queryValue: '黎巴嫩', sortKey: 'Lebanon' },
  { code: 'LS', label: '莱索托', value: '莱索托', queryValue: '莱索托', sortKey: 'Lesotho' },
  { code: 'LR', label: '利比里亚', value: '利比里亚', queryValue: '利比里亚', sortKey: 'Liberia' },
  { code: 'LY', label: '利比亚', value: '利比亚', queryValue: '利比亚', sortKey: 'Libya' },
  { code: 'LI', label: '列支敦士登', value: '列支敦士登', queryValue: '列支敦士登', sortKey: 'Liechtenstein' },
  { code: 'LT', label: '立陶宛', value: '立陶宛', queryValue: '立陶宛', sortKey: 'Lithuania' },
  { code: 'LU', label: '卢森堡', value: '卢森堡', queryValue: '卢森堡', sortKey: 'Luxembourg' },
  { code: 'MO', label: '澳门', value: '澳门', queryValue: '澳门', sortKey: 'Macao' },
  { code: 'MG', label: '马达加斯加', value: '马达加斯加', queryValue: '马达加斯加', sortKey: 'Madagascar' },
  { code: 'MW', label: '马拉维', value: '马拉维', queryValue: '马拉维', sortKey: 'Malawi' },
  { code: 'MY', label: '马来西亚', value: '马来西亚', queryValue: '马来西亚', sortKey: 'Malaysia' },
  { code: 'MV', label: '马尔代夫', value: '马尔代夫', queryValue: '马尔代夫', sortKey: 'Maldives' },
  { code: 'ML', label: '马里', value: '马里', queryValue: '马里', sortKey: 'Mali' },
  { code: 'MT', label: '马耳他', value: '马耳他', queryValue: '马耳他', sortKey: 'Malta' },
  { code: 'MH', label: '马绍尔群岛', value: '马绍尔群岛', queryValue: '马绍尔群岛', sortKey: 'Marshall Islands (the)' },
  { code: 'MQ', label: '马提尼克', value: '马提尼克', queryValue: '马提尼克', sortKey: 'Martinique' },
  { code: 'MR', label: '毛里塔尼亚', value: '毛里塔尼亚', queryValue: '毛里塔尼亚', sortKey: 'Mauritania' },
  { code: 'MU', label: '毛里求斯', value: '毛里求斯', queryValue: '毛里求斯', sortKey: 'Mauritius' },
  { code: 'YT', label: '马约特', value: '马约特', queryValue: '马约特', sortKey: 'Mayotte' },
  { code: 'MX', label: '墨西哥', value: '墨西哥', queryValue: '墨西哥', sortKey: 'Mexico' },
  { code: 'FM', label: '密克罗尼西亚联邦', value: '密克罗尼西亚联邦', queryValue: '密克罗尼西亚联邦', sortKey: 'Micronesia (the Federated States of)' },
  { code: 'MD', label: '摩尔多瓦', value: '摩尔多瓦', queryValue: '摩尔多瓦', sortKey: 'Moldova' },
  { code: 'MC', label: '摩纳哥', value: '摩纳哥', queryValue: '摩纳哥', sortKey: 'Monaco' },
  { code: 'MN', label: '蒙古', value: '蒙古', queryValue: '蒙古', sortKey: 'Mongolia' },
  { code: 'ME', label: '黑山', value: '黑山', queryValue: '黑山', sortKey: 'Montenegro' },
  { code: 'MS', label: '蒙特塞拉特', value: '蒙特塞拉特', queryValue: '蒙特塞拉特', sortKey: 'Montserrat' },
  { code: 'MA', label: '摩洛哥', value: '摩洛哥', queryValue: '摩洛哥', sortKey: 'Morocco' },
  { code: 'MZ', label: '莫桑比克', value: '莫桑比克', queryValue: '莫桑比克', sortKey: 'Mozambique' },
  { code: 'NA', label: '纳米比亚', value: '纳米比亚', queryValue: '纳米比亚', sortKey: 'Namibia' },
  { code: 'NR', label: '瑙鲁', value: '瑙鲁', queryValue: '瑙鲁', sortKey: 'Nauru' },
  { code: 'NP', label: '尼泊尔', value: '尼泊尔', queryValue: '尼泊尔', sortKey: 'Nepal' },
  { code: 'NL', label: '荷兰', value: '荷兰', queryValue: '荷兰', sortKey: 'Netherlands(Holland)' },
  { code: 'NC', label: '新喀里多尼亚', value: '新喀里多尼亚', queryValue: '新喀里多尼亚', sortKey: 'New Caledonia' },
  { code: 'NZ', label: '新西兰', value: '新西兰', queryValue: '新西兰', sortKey: 'New Zealand' },
  { code: 'NI', label: '尼加拉瓜', value: '尼加拉瓜', queryValue: '尼加拉瓜', sortKey: 'Nicaragua' },
  { code: 'NE', label: '尼日尔', value: '尼日尔', queryValue: '尼日尔', sortKey: 'Niger' },
  { code: 'NG', label: '尼日利亚', value: '尼日利亚', queryValue: '尼日利亚', sortKey: 'Nigeria' },
  { code: 'NU', label: '纽埃', value: '纽埃', queryValue: '纽埃', sortKey: 'Niue' },
  { code: 'NF', label: '诺福克岛', value: '诺福克岛', queryValue: '诺福克岛', sortKey: 'Norfolk Island' },
  { code: 'KP', label: '朝鲜', value: '朝鲜', queryValue: '朝鲜', sortKey: 'North Korea' },
  { code: 'MK', label: '北马其顿', value: '北马其顿', queryValue: '北马其顿', sortKey: 'North Macedonia' },
  { code: 'MP', label: '北马里亚纳群岛', value: '北马里亚纳群岛', queryValue: '北马里亚纳群岛', sortKey: 'Northern Mariana Islands' },
  { code: 'NO', label: '挪威', value: '挪威', queryValue: '挪威', sortKey: 'Norway' },
  { code: 'OM', label: '阿曼', value: '阿曼', queryValue: '阿曼', sortKey: 'Oman' },
  { code: 'PK', label: '巴基斯坦', value: '巴基斯坦', queryValue: '巴基斯坦', sortKey: 'Pakistan' },
  { code: 'PW', label: '帕劳', value: '帕劳', queryValue: '帕劳', sortKey: 'Palau' },
  { code: 'PS', label: '巴勒斯坦', value: '巴勒斯坦', queryValue: '巴勒斯坦', sortKey: 'Palestinian Territory (the Occupied)' },
  { code: 'PA', label: '巴拿马', value: '巴拿马', queryValue: '巴拿马', sortKey: 'Panama' },
  { code: 'PG', label: '巴布亚新几内亚', value: '巴布亚新几内亚', queryValue: '巴布亚新几内亚', sortKey: 'Papua New Guinea' },
  { code: 'PY', label: '巴拉圭', value: '巴拉圭', queryValue: '巴拉圭', sortKey: 'Paraguay' },
  { code: 'PE', label: '秘鲁', value: '秘鲁', queryValue: '秘鲁', sortKey: 'Peru' },
  { code: 'PH', label: '菲律宾', value: '菲律宾', queryValue: '菲律宾', sortKey: 'Philippines' },
  { code: 'PL', label: '波兰', value: '波兰', queryValue: '波兰', sortKey: 'Poland' },
  { code: 'PT', label: '葡萄牙', value: '葡萄牙', queryValue: '葡萄牙', sortKey: 'Portugal' },
  { code: 'PR', label: '波多黎各', value: '波多黎各', queryValue: '波多黎各', sortKey: 'Puerto Rico' },
  { code: 'QA', label: '卡塔尔', value: '卡塔尔', queryValue: '卡塔尔', sortKey: 'Qatar' },
  { code: 'RO', label: '罗马尼亚', value: '罗马尼亚', queryValue: '罗马尼亚', sortKey: 'Romania' },
  { code: 'RU', label: '俄罗斯', value: '俄罗斯', queryValue: '俄罗斯', sortKey: 'Russian Federation' },
  { code: 'RW', label: '卢旺达', value: '卢旺达', queryValue: '卢旺达', sortKey: 'Rwanda' },
  { code: 'RE', label: '留尼汪', value: '留尼汪', queryValue: '留尼汪', sortKey: 'Réunion' },
  { code: 'BL', label: '圣巴泰勒米', value: '圣巴泰勒米', queryValue: '圣巴泰勒米', sortKey: 'Saint Barthelemy' },
  { code: 'KN', label: '圣基茨和尼维斯', value: '圣基茨和尼维斯', queryValue: '圣基茨和尼维斯', sortKey: 'Saint Kitts and Nevis' },
  { code: 'LC', label: '圣卢西亚', value: '圣卢西亚', queryValue: '圣卢西亚', sortKey: 'Saint Lucia' },
  { code: 'MF', label: '法属圣马丁', value: '法属圣马丁', queryValue: '法属圣马丁', sortKey: 'Saint Martin (France)' },
  { code: 'PM', label: '圣皮埃尔和密克隆', value: '圣皮埃尔和密克隆', queryValue: '圣皮埃尔和密克隆', sortKey: 'Saint Pierre and Miquelon' },
  { code: 'VC', label: '圣文森特和格林纳丁斯', value: '圣文森特和格林纳丁斯', queryValue: '圣文森特和格林纳丁斯', sortKey: 'Saint Vincent and the Grenadines' },
  { code: 'WS', label: '萨摩亚', value: '萨摩亚', queryValue: '萨摩亚', sortKey: 'Samoa' },
  { code: 'SM', label: '圣马力诺', value: '圣马力诺', queryValue: '圣马力诺', sortKey: 'San Marino' },
  { code: 'ST', label: '圣多美和普林西比', value: '圣多美和普林西比', queryValue: '圣多美和普林西比', sortKey: 'Sao Tome and Principe' },
  { code: 'SA', label: '沙特阿拉伯', value: '沙特阿拉伯', queryValue: '沙特阿拉伯', sortKey: 'Saudi Arabia' },
  { code: 'SN', label: '塞内加尔', value: '塞内加尔', queryValue: '塞内加尔', sortKey: 'Senegal' },
  { code: 'RS', label: '塞尔维亚', value: '塞尔维亚', queryValue: '塞尔维亚', sortKey: 'Serbia' },
  { code: 'SC', label: '塞舌尔', value: '塞舌尔', queryValue: '塞舌尔', sortKey: 'Seychelles' },
  { code: 'SL', label: '塞拉利昂', value: '塞拉利昂', queryValue: '塞拉利昂', sortKey: 'Sierra Leone' },
  { code: 'SG', label: '新加坡', value: '新加坡', queryValue: '新加坡', sortKey: 'Singapore' },
  { code: 'SX', label: '荷属圣马丁', value: '荷属圣马丁', queryValue: '荷属圣马丁', sortKey: 'Sint Maarten' },
  { code: 'SK', label: '斯洛伐克', value: '斯洛伐克', queryValue: '斯洛伐克', sortKey: 'Slovakia' },
  { code: 'SI', label: '斯洛文尼亚', value: '斯洛文尼亚', queryValue: '斯洛文尼亚', sortKey: 'Slovenia' },
  { code: 'SB', label: '所罗门群岛', value: '所罗门群岛', queryValue: '所罗门群岛', sortKey: 'Solomon Islands' },
  { code: 'SO', label: '索马里', value: '索马里', queryValue: '索马里', sortKey: 'Somalia' },
  { code: 'ZA', label: '南非', value: '南非', queryValue: '南非', sortKey: 'South Africa' },
  { code: 'KR', label: '韩国', value: '韩国', queryValue: '韩国', sortKey: 'South Korea' },
  { code: 'SS', label: '南苏丹', value: '南苏丹', queryValue: '南苏丹', sortKey: 'South Sudan' },
  { code: 'ES', label: '西班牙', value: '西班牙', queryValue: '西班牙', sortKey: 'Spain' },
  { code: 'LK', label: '斯里兰卡', value: '斯里兰卡', queryValue: '斯里兰卡', sortKey: 'Sri Lanka' },
  { code: 'SD', label: '苏丹', value: '苏丹', queryValue: '苏丹', sortKey: 'Sudan' },
  { code: 'SR', label: '苏里南', value: '苏里南', queryValue: '苏里南', sortKey: 'Suriname' },
  { code: 'SZ', label: '斯威士兰', value: '斯威士兰', queryValue: '斯威士兰', sortKey: 'Swaziland' },
  { code: 'SE', label: '瑞典', value: '瑞典', queryValue: '瑞典', sortKey: 'Sweden' },
  { code: 'CH', label: '瑞士', value: '瑞士', queryValue: '瑞士', sortKey: 'Switzerland' },
  { code: 'SY', label: '叙利亚', value: '叙利亚', queryValue: '叙利亚', sortKey: 'Syria' },
  { code: 'TW', label: '中国台湾', value: '中国台湾', queryValue: '中国台湾省', sortKey: 'Taiwan (Province of China)' },
  { code: 'TJ', label: '塔吉克斯坦', value: '塔吉克斯坦', queryValue: '塔吉克斯坦', sortKey: 'Tajikistan' },
  { code: 'TZ', label: '坦桑尼亚', value: '坦桑尼亚', queryValue: '坦桑尼亚', sortKey: 'Tanzania' },
  { code: 'TH', label: '泰国', value: '泰国', queryValue: '泰国', sortKey: 'Thailand' },
  { code: 'TL', label: '东帝汶', value: '东帝汶', queryValue: '东帝汶', sortKey: 'Timor-Leste' },
  { code: 'TG', label: '多哥', value: '多哥', queryValue: '多哥', sortKey: 'Togo' },
  { code: 'TK', label: '托克劳', value: '托克劳', queryValue: '托克劳', sortKey: 'Tokelau' },
  { code: 'TO', label: '汤加', value: '汤加', queryValue: '汤加', sortKey: 'Tonga' },
  { code: 'TT', label: '特立尼达和多巴哥', value: '特立尼达和多巴哥', queryValue: '特立尼达和多巴哥', sortKey: 'Trinidad and Tobago' },
  { code: 'TN', label: '突尼斯', value: '突尼斯', queryValue: '突尼斯', sortKey: 'Tunisia' },
  { code: 'TR', label: '土耳其', value: '土耳其', queryValue: '土耳其', sortKey: 'Turkey' },
  { code: 'TM', label: '土库曼斯坦', value: '土库曼斯坦', queryValue: '土库曼斯坦', sortKey: 'Turkmenistan' },
  { code: 'TC', label: '特克斯和凯科斯群岛', value: '特克斯和凯科斯群岛', queryValue: '特克斯和凯科斯群岛', sortKey: 'Turks and Caicos Islands (the)' },
  { code: 'TV', label: '图瓦卢', value: '图瓦卢', queryValue: '图瓦卢', sortKey: 'Tuvalu' },
  { code: 'UG', label: '乌干达', value: '乌干达', queryValue: '乌干达', sortKey: 'Uganda' },
  { code: 'UA', label: '乌克兰', value: '乌克兰', queryValue: '乌克兰', sortKey: 'Ukraine' },
  { code: 'AE', label: '阿拉伯联合酋长国', value: '阿拉伯联合酋长国', queryValue: '阿联酋', sortKey: 'United Arab Emirates' },
  { code: 'GB', label: '英国', value: '英国', queryValue: '英国', sortKey: 'United Kingdom' },
  { code: 'US', label: '美国', value: '美国', queryValue: '美国', sortKey: 'United States' },
  { code: 'UY', label: '乌拉圭', value: '乌拉圭', queryValue: '乌拉圭', sortKey: 'Uruguay' },
  { code: 'UZ', label: '乌兹别克斯坦', value: '乌兹别克斯坦', queryValue: '乌兹别克斯坦', sortKey: 'Uzbekistan' },
  { code: 'VU', label: '瓦努阿图', value: '瓦努阿图', queryValue: '瓦努阿图', sortKey: 'Vanuatu' },
  { code: 'VA', label: '梵蒂冈', value: '梵蒂冈', queryValue: '梵蒂冈', sortKey: 'Vaticano' },
  { code: 'VE', label: '委内瑞拉', value: '委内瑞拉', queryValue: '委内瑞拉', sortKey: 'Venezuela' },
  { code: 'VN', label: '越南', value: '越南', queryValue: '越南', sortKey: 'VietNam' },
  { code: 'VG', label: '英属维尔京群岛', value: '英属维尔京群岛', queryValue: '英属维尔京群岛', sortKey: 'Virgin Islands (British)' },
  { code: 'VI', label: '美属维尔京群岛', value: '美属维尔京群岛', queryValue: '美属维尔京群岛', sortKey: 'Virgin Islands (U.S.)' },
  { code: 'WF', label: '瓦利斯和富图纳', value: '瓦利斯和富图纳', queryValue: '瓦利斯和富图纳', sortKey: 'Wallis and Futuna' },
  { code: 'YE', label: '也门', value: '也门', queryValue: '也门', sortKey: 'Yemen' },
  { code: 'ZM', label: '赞比亚', value: '赞比亚', queryValue: '赞比亚', sortKey: 'Zambia' },
  { code: 'ZW', label: '津巴布韦', value: '津巴布韦', queryValue: '津巴布韦', sortKey: 'Zimbabwe' },
];

export const COUNTRY_QUERY_ALIASES: Record<string, string> = {
  '不丹': '不丹',
  '东帝汶': '东帝汶',
  '中国': '中国',
  '中国台湾': '中国台湾省',
  '中国台湾省': '中国台湾省',
  '中非': '中非',
  '丹麦': '丹麦',
  '乌克兰': '乌克兰',
  '乌兹别克斯坦': '乌兹别克斯坦',
  '乌干达': '乌干达',
  '乌拉圭': '乌拉圭',
  '乍得': '乍得',
  '也门': '也门',
  '亚太地区': '亚太地区',
  '亚美尼亚': '亚美尼亚',
  '以色列': '以色列',
  '伊拉克': '伊拉克',
  '伊朗': '伊朗',
  '伯利兹': '伯利兹',
  '佛得角': '佛得角',
  '俄罗斯': '俄罗斯',
  '保加利亚': '保加利亚',
  '克罗地亚': '克罗地亚',
  '关岛': '关岛',
  '冈比亚': '冈比亚',
  '冰岛': '冰岛',
  '几内亚': '几内亚',
  '几内亚比绍': '几内亚比绍',
  '列支敦士登': '列支敦士登',
  '刚果共和国': '刚果共和国',
  '刚果民主共和国': '刚果民主共和国',
  '刚果（布）': '刚果共和国',
  '刚果（金）': '刚果民主共和国',
  '利比亚': '利比亚',
  '利比里亚': '利比里亚',
  '前南马其顿': '北马其顿',
  '加拿大': '加拿大',
  '加纳': '加纳',
  '加蓬': '加蓬',
  '匈牙利': '匈牙利',
  '北马其顿': '北马其顿',
  '北马里亚纳': '北马里亚纳群岛',
  '北马里亚纳群岛': '北马里亚纳群岛',
  '南苏丹': '南苏丹',
  '南非': '南非',
  '博茨瓦纳': '博茨瓦纳',
  '卡塔尔': '卡塔尔',
  '卢旺达': '卢旺达',
  '卢森堡': '卢森堡',
  '印度': '印度',
  '印度尼西亚': '印度尼西亚',
  '危地马拉': '危地马拉',
  '厄瓜多尔': '厄瓜多尔',
  '厄立特里亚': '厄立特里亚',
  '叙利亚': '叙利亚',
  '古巴': '古巴',
  '吉尔吉斯斯坦': '吉尔吉斯斯坦',
  '吉布提': '吉布提',
  '哈萨克斯坦': '哈萨克斯坦',
  '哥伦比亚': '哥伦比亚',
  '哥斯达黎加': '哥斯达黎加',
  '喀麦隆': '喀麦隆',
  '图瓦卢': '图瓦卢',
  '土库曼斯坦': '土库曼斯坦',
  '土耳其': '土耳其',
  '圣卢西亚': '圣卢西亚',
  '圣基茨和尼维斯': '圣基茨和尼维斯',
  '圣多美和普林西比': '圣多美和普林西比',
  '圣巴泰勒米': '圣巴泰勒米',
  '圣巴泰勒米岛': '圣巴泰勒米',
  '圣文森特和格林纳丁斯': '圣文森特和格林纳丁斯',
  '圣皮埃尔和密克隆': '圣皮埃尔和密克隆',
  '圣马力诺': '圣马力诺',
  '圭亚那': '圭亚那',
  '坦桑尼亚': '坦桑尼亚',
  '埃及': '埃及',
  '埃塞俄比亚': '埃塞俄比亚',
  '基里巴斯': '基里巴斯',
  '塔吉克斯坦': '塔吉克斯坦',
  '塞内加尔': '塞内加尔',
  '塞尔维亚': '塞尔维亚',
  '塞拉利昂': '塞拉利昂',
  '塞浦路斯': '塞浦路斯',
  '塞舌尔': '塞舌尔',
  '墨西哥': '墨西哥',
  '多哥': '多哥',
  '多米尼克': '多米尼克',
  '多米尼加': '多米尼加',
  '奥兰': '奥兰',
  '奥兰群岛': '奥兰',
  '奥地利': '奥地利',
  '委内瑞拉': '委内瑞拉',
  '孟加拉国': '孟加拉国',
  '安哥拉': '安哥拉',
  '安圭拉': '安圭拉',
  '安提瓜和巴布达': '安提瓜和巴布达',
  '安道尔': '安道尔',
  '密克罗尼西亚联邦': '密克罗尼西亚联邦',
  '尼加拉瓜': '尼加拉瓜',
  '尼日利亚': '尼日利亚',
  '尼日尔': '尼日尔',
  '尼泊尔': '尼泊尔',
  '巴勒斯坦': '巴勒斯坦',
  '巴哈马': '巴哈马',
  '巴基斯坦': '巴基斯坦',
  '巴巴多斯': '巴巴多斯',
  '巴布亚新几内亚': '巴布亚新几内亚',
  '巴拉圭': '巴拉圭',
  '巴拿马': '巴拿马',
  '巴林': '巴林',
  '巴西': '巴西',
  '布基纳法索': '布基纳法索',
  '布隆迪': '布隆迪',
  '希腊': '希腊',
  '帕劳': '帕劳',
  '库克群岛': '库克群岛',
  '库拉索': '库拉索',
  '开曼群岛': '开曼群岛',
  '德国': '德国',
  '意大利': '意大利',
  '所罗门群岛': '所罗门群岛',
  '托克劳': '托克劳',
  '拉脱维亚': '拉脱维亚',
  '挪威': '挪威',
  '捷克': '捷克',
  '摩尔多瓦': '摩尔多瓦',
  '摩洛哥': '摩洛哥',
  '摩纳哥': '摩纳哥',
  '文莱': '文莱',
  '斐济': '斐济',
  '斯威士兰': '斯威士兰',
  '斯洛伐克': '斯洛伐克',
  '斯洛文尼亚': '斯洛文尼亚',
  '斯里兰卡': '斯里兰卡',
  '新加坡': '新加坡',
  '新喀里多尼亚': '新喀里多尼亚',
  '新西兰': '新西兰',
  '日本': '日本',
  '智利': '智利',
  '朝鲜': '朝鲜',
  '柬埔寨': '柬埔寨',
  '根西': '根西',
  '格恩西岛': '根西',
  '格林纳达': '格林纳达',
  '格陵兰': '格陵兰',
  '格鲁吉亚': '格鲁吉亚',
  '梵蒂冈': '梵蒂冈',
  '欧盟': '欧盟',
  '比利时': '比利时',
  '毛利塔尼亚': '毛里塔尼亚',
  '毛里塔尼亚': '毛里塔尼亚',
  '毛里求斯': '毛里求斯',
  '汤加': '汤加',
  '沙特阿拉伯': '沙特阿拉伯',
  '法国': '法国',
  '法属圣马丁': '法属圣马丁',
  '法属圭亚那': '法属圭亚那',
  '法属波利尼西亚': '法属波利尼西亚',
  '法罗群岛': '法罗群岛',
  '波兰': '波兰',
  '波多黎各': '波多黎各',
  '波黑': '波黑',
  '泰国': '泰国',
  '泽西': '泽西',
  '泽西岛': '泽西',
  '津巴布韦': '津巴布韦',
  '洪都拉斯': '洪都拉斯',
  '海地': '海地',
  '澳大利亚': '澳大利亚',
  '澳门': '澳门',
  '爱尔兰': '爱尔兰',
  '爱沙尼亚': '爱沙尼亚',
  '牙买加': '牙买加',
  '特克斯和凯科斯群岛': '特克斯和凯科斯群岛',
  '特立尼达和多巴哥': '特立尼达和多巴哥',
  '玻利维亚': '玻利维亚',
  '瑙鲁': '瑙鲁',
  '瑞典': '瑞典',
  '瑞士': '瑞士',
  '瓜德罗普': '瓜德罗普',
  '瓦利斯和富图纳': '瓦利斯和富图纳',
  '瓦努阿图': '瓦努阿图',
  '留尼汪': '留尼汪',
  '白俄罗斯': '白俄罗斯',
  '百慕大': '百慕大',
  '直布罗陀': '直布罗陀',
  '福克兰群岛': '福克兰群岛',
  '福克兰群岛（马尔维纳斯）': '福克兰群岛',
  '科威特': '科威特',
  '科摩罗': '科摩罗',
  '科特迪瓦': '科特迪瓦',
  '秘鲁': '秘鲁',
  '突尼斯': '突尼斯',
  '立陶宛': '立陶宛',
  '索马里': '索马里',
  '约旦': '约旦',
  '纳米比亚': '纳米比亚',
  '纽埃': '纽埃',
  '缅甸': '缅甸',
  '罗马尼亚': '罗马尼亚',
  '美国': '美国',
  '美属维尔京群岛': '美属维尔京群岛',
  '美属萨摩亚': '美属萨摩亚',
  '老挝': '老挝',
  '肯尼亚': '肯尼亚',
  '芬兰': '芬兰',
  '苏丹': '苏丹',
  '苏里南': '苏里南',
  '英国': '英国',
  '英国属地曼岛': '马恩岛',
  '英属印度洋领地': '英属印度洋领地',
  '英属维尔京群岛': '英属维尔京群岛',
  '荷兰': '荷兰',
  '荷兰加勒比区': '荷兰加勒比区',
  '荷属圣马丁': '荷属圣马丁',
  '莫桑比克': '莫桑比克',
  '莱索托': '莱索托',
  '菲律宾': '菲律宾',
  '萨尔瓦多': '萨尔瓦多',
  '萨摩亚': '萨摩亚',
  '葡萄牙': '葡萄牙',
  '蒙古': '蒙古',
  '蒙特塞拉特': '蒙特塞拉特',
  '西班牙': '西班牙',
  '诺福克岛': '诺福克岛',
  '贝宁': '贝宁',
  '赞比亚': '赞比亚',
  '赤道几内亚': '赤道几内亚',
  '越南': '越南',
  '阿塞拜疆': '阿塞拜疆',
  '阿富汗': '阿富汗',
  '阿尔及利亚': '阿尔及利亚',
  '阿尔巴尼亚': '阿尔巴尼亚',
  '阿拉伯联合酋长国': '阿联酋',
  '阿曼': '阿曼',
  '阿根廷': '阿根廷',
  '阿联酋': '阿联酋',
  '阿鲁巴': '阿鲁巴',
  '韩国': '韩国',
  '香港': '香港',
  '马尔代夫': '马尔代夫',
  '马恩岛': '马恩岛',
  '马拉维': '马拉维',
  '马提尼克': '马提尼克',
  '马来西亚': '马来西亚',
  '马约特': '马约特',
  '马绍尔群岛': '马绍尔群岛',
  '马耳他': '马耳他',
  '马达加斯加': '马达加斯加',
  '马里': '马里',
  '黎巴嫩': '黎巴嫩',
  '黑山': '黑山',
};
